<?php

namespace Agencia\BaseDatosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrabajosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajosRepository extends EntityRepository
{
}
