agencia_base_datos_homepage:
    path:     /
    defaults: { _controller: AgenciaBaseDatosBundle:Trabajos:index }

agencia_base_datos_agencia_trabajos:
    resource: "@AgenciaBaseDatosBundle/Resources/config/routing/trabajos.yml"
    prefix:   /trabajos


